// <auto-generated />
using System;
using Kentos.Modules.Settlement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kentos.Modules.Settlement.Infrastructure.Migrations
{
    [DbContext(typeof(SettlementDbContext))]
    [Migration("20260626040727_InitialSettlement")]
    partial class InitialSettlement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("yerlesim")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kentos.Modules.Settlement.Domain.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ad")
                        .HasComment("İlçe adı");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint")
                        .HasColumnName("il_id")
                        .HasComment("İl yabancı anahtarı");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_ilceler");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_ilceler_uuid");

                    b.HasIndex("ProvinceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ilceler_il_id_ad");

                    b.ToTable("ilceler", "yerlesim", t =>
                        {
                            t.HasComment("İlçeler");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Settlement.Domain.Neighborhood", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<MultiPolygon>("Boundary")
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("sinir")
                        .HasComment("Sınır çokgeni (SRID 4326)");

                    b.Property<Point>("Center")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("merkez")
                        .HasComment("Merkez nokta (SRID 4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("ilce_id")
                        .HasComment("İlçe yabancı anahtarı");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ad")
                        .HasComment("Mahalle adı");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("posta_kodu")
                        .HasComment("Posta kodu");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_mahalleler");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_mahalleler_uuid");

                    b.HasIndex("DistrictId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mahalleler_ilce_id_ad");

                    b.ToTable("mahalleler", "yerlesim", t =>
                        {
                            t.HasComment("Mahalleler");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Settlement.Domain.Province", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ad")
                        .HasComment("İl adı");

                    b.Property<int>("PlateCode")
                        .HasColumnType("integer")
                        .HasColumnName("plaka_kodu")
                        .HasComment("Plaka kodu (1..81)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_iller");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_iller_ad");

                    b.HasIndex("PlateCode")
                        .IsUnique()
                        .HasDatabaseName("ix_iller_plaka_kodu");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_iller_uuid");

                    b.ToTable("iller", "yerlesim", t =>
                        {
                            t.HasComment("İller");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Settlement.Domain.District", b =>
                {
                    b.HasOne("Kentos.Modules.Settlement.Domain.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ilceler_provinces_province_id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Kentos.Modules.Settlement.Domain.Neighborhood", b =>
                {
                    b.HasOne("Kentos.Modules.Settlement.Domain.District", "District")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mahalleler_ilceler_district_id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Kentos.Modules.Settlement.Domain.District", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("Kentos.Modules.Settlement.Domain.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
