// AUTO-GENERATED by scripts/gen.mjs — do not edit. Regenerate with `pnpm gen`.
import type { paths } from "./schema";
import { createApiClient, type ApiClientOptions } from "../../client";
import { createSettlementSdk } from "./sdk";

/** Ham tipli openapi-fetch client (`settlement` modülü). */
export function createSettlementClient(options: ApiClientOptions) {
  return createApiClient<paths>(options);
}

/** Adlandırılmış, permission-yorumlu SDK. */
export function createSettlementApi(options: ApiClientOptions) {
  return createSettlementSdk(createSettlementClient(options));
}

export type { paths, components, operations } from "./schema";
export * from "./sdk";
export * from "./queries";
