// AUTO-GENERATED by scripts/gen.mjs — do not edit. Regenerate with `pnpm gen`.
import { useMutation, useQuery, useQueryClient, type UseMutationOptions, type UseQueryOptions } from "@tanstack/react-query";
import type { FetchOptions } from "openapi-fetch";
import type { paths } from "./schema";
import { createSettlementSdk } from "./sdk";

type Sdk = ReturnType<typeof createSettlementSdk>;
type Data<M extends keyof Sdk> = NonNullable<Awaited<ReturnType<Sdk[M]>>["data"]>;

/**
 * `settlement` modülü TanStack Query hook'ları (SDK üstünde cache + mutation yönetimi).
 * Her hook'un üzerinde gerekli **permission** JSDoc olarak yazılıdır. Bir kez `sdk` ile
 * kurun (web: configured client; RN: aynısı), dönen hook'ları bileşenlerde kullanın.
 */
export function createSettlementQueries(sdk: Sdk) {
  return {
    /**
     * İlçe getir
     * @route GET /api/v1/settlement/districts/{id}
     * @permission settlement.district.view
     */
    useGetDistrictsById(init: FetchOptions<paths["/api/v1/settlement/districts/{id}"]["get"]>, options?: Omit<UseQueryOptions<Data<"getDistrictsById">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getDistrictsById">, Error>({
        queryKey: ["settlement", "/api/v1/settlement/districts/{id}", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getDistrictsById(init);
          if (error) throw error as Error;
          return data as Data<"getDistrictsById">;
        },
        ...options,
      });
    },
    /**
     * İlçeleri listele
     * @route GET /api/v1/settlement/districts
     * @permission settlement.district.list
     */
    useGetDistricts(init?: FetchOptions<paths["/api/v1/settlement/districts"]["get"]>, options?: Omit<UseQueryOptions<Data<"getDistricts">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getDistricts">, Error>({
        queryKey: ["settlement", "/api/v1/settlement/districts", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getDistricts(init);
          if (error) throw error as Error;
          return data as Data<"getDistricts">;
        },
        ...options,
      });
    },
    /**
     * İlçe ekle
     * @route POST /api/v1/settlement/districts
     * @permission settlement.district.create
     */
    usePostDistricts(options?: Omit<UseMutationOptions<Data<"postDistricts">, Error, FetchOptions<paths["/api/v1/settlement/districts"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postDistricts">, Error, FetchOptions<paths["/api/v1/settlement/districts"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postDistricts(init);
          if (error) throw error as Error;
          return data as Data<"postDistricts">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "settlement" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/settlement/districts"),
          });
        },
        ...options,
      });
    },
    /**
     * Mahalle sil
     * @route DELETE /api/v1/settlement/neighborhoods/{id}
     * @permission settlement.neighborhood.delete
     */
    useDeleteNeighborhoodsById(options?: Omit<UseMutationOptions<Data<"deleteNeighborhoodsById">, Error, FetchOptions<paths["/api/v1/settlement/neighborhoods/{id}"]["delete"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"deleteNeighborhoodsById">, Error, FetchOptions<paths["/api/v1/settlement/neighborhoods/{id}"]["delete"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.deleteNeighborhoodsById(init);
          if (error) throw error as Error;
          return data as Data<"deleteNeighborhoodsById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "settlement" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/settlement/neighborhoods"),
          });
        },
        ...options,
      });
    },
    /**
     * Mahalle getir
     * @route GET /api/v1/settlement/neighborhoods/{id}
     * @permission settlement.neighborhood.view
     */
    useGetNeighborhoodsById(init: FetchOptions<paths["/api/v1/settlement/neighborhoods/{id}"]["get"]>, options?: Omit<UseQueryOptions<Data<"getNeighborhoodsById">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getNeighborhoodsById">, Error>({
        queryKey: ["settlement", "/api/v1/settlement/neighborhoods/{id}", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getNeighborhoodsById(init);
          if (error) throw error as Error;
          return data as Data<"getNeighborhoodsById">;
        },
        ...options,
      });
    },
    /**
     * Mahalle güncelle
     * @route PUT /api/v1/settlement/neighborhoods/{id}
     * @permission settlement.neighborhood.update
     */
    usePutNeighborhoodsById(options?: Omit<UseMutationOptions<Data<"putNeighborhoodsById">, Error, FetchOptions<paths["/api/v1/settlement/neighborhoods/{id}"]["put"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"putNeighborhoodsById">, Error, FetchOptions<paths["/api/v1/settlement/neighborhoods/{id}"]["put"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.putNeighborhoodsById(init);
          if (error) throw error as Error;
          return data as Data<"putNeighborhoodsById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "settlement" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/settlement/neighborhoods"),
          });
        },
        ...options,
      });
    },
    /**
     * Mahalleleri listele
     * @route GET /api/v1/settlement/neighborhoods
     * @permission settlement.neighborhood.list
     */
    useGetNeighborhoods(init?: FetchOptions<paths["/api/v1/settlement/neighborhoods"]["get"]>, options?: Omit<UseQueryOptions<Data<"getNeighborhoods">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getNeighborhoods">, Error>({
        queryKey: ["settlement", "/api/v1/settlement/neighborhoods", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getNeighborhoods(init);
          if (error) throw error as Error;
          return data as Data<"getNeighborhoods">;
        },
        ...options,
      });
    },
    /**
     * Mahalle ekle
     * @route POST /api/v1/settlement/neighborhoods
     * @permission settlement.neighborhood.create
     */
    usePostNeighborhoods(options?: Omit<UseMutationOptions<Data<"postNeighborhoods">, Error, FetchOptions<paths["/api/v1/settlement/neighborhoods"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postNeighborhoods">, Error, FetchOptions<paths["/api/v1/settlement/neighborhoods"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postNeighborhoods(init);
          if (error) throw error as Error;
          return data as Data<"postNeighborhoods">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "settlement" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/settlement/neighborhoods"),
          });
        },
        ...options,
      });
    },
    /**
     * İl getir
     * @route GET /api/v1/settlement/provinces/{id}
     * @permission settlement.province.view
     */
    useGetProvincesById(init: FetchOptions<paths["/api/v1/settlement/provinces/{id}"]["get"]>, options?: Omit<UseQueryOptions<Data<"getProvincesById">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getProvincesById">, Error>({
        queryKey: ["settlement", "/api/v1/settlement/provinces/{id}", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getProvincesById(init);
          if (error) throw error as Error;
          return data as Data<"getProvincesById">;
        },
        ...options,
      });
    },
    /**
     * İlleri listele
     * @route GET /api/v1/settlement/provinces
     * @permission settlement.province.list
     */
    useGetProvinces(init?: FetchOptions<paths["/api/v1/settlement/provinces"]["get"]>, options?: Omit<UseQueryOptions<Data<"getProvinces">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getProvinces">, Error>({
        queryKey: ["settlement", "/api/v1/settlement/provinces", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getProvinces(init);
          if (error) throw error as Error;
          return data as Data<"getProvinces">;
        },
        ...options,
      });
    },
    /**
     * İl ekle
     * @route POST /api/v1/settlement/provinces
     * @permission settlement.province.create
     */
    usePostProvinces(options?: Omit<UseMutationOptions<Data<"postProvinces">, Error, FetchOptions<paths["/api/v1/settlement/provinces"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postProvinces">, Error, FetchOptions<paths["/api/v1/settlement/provinces"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postProvinces(init);
          if (error) throw error as Error;
          return data as Data<"postProvinces">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "settlement" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/settlement/provinces"),
          });
        },
        ...options,
      });
    },
  };
}
