/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/settlement/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * İlçeleri listele
         * @description **Permission:** `settlement.district.list`
         */
        get: {
            parameters: {
                query?: {
                    ProvinceId?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfDistrictResponse"];
                        "application/json": components["schemas"]["PagedResponseOfDistrictResponse"];
                        "text/json": components["schemas"]["PagedResponseOfDistrictResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * İlçe ekle
         * @description **Permission:** `settlement.district.create`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDistrictCommand"];
                    "text/json": components["schemas"]["CreateDistrictCommand"];
                    "application/*+json": components["schemas"]["CreateDistrictCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DistrictResponse"];
                        "application/json": components["schemas"]["DistrictResponse"];
                        "text/json": components["schemas"]["DistrictResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/districts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * İlçe getir
         * @description **Permission:** `settlement.district.view`
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DistrictResponse"];
                        "application/json": components["schemas"]["DistrictResponse"];
                        "text/json": components["schemas"]["DistrictResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/neighborhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mahalleleri listele
         * @description **Permission:** `settlement.neighborhood.list`
         */
        get: {
            parameters: {
                query?: {
                    DistrictId?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfNeighborhoodResponse"];
                        "application/json": components["schemas"]["PagedResponseOfNeighborhoodResponse"];
                        "text/json": components["schemas"]["PagedResponseOfNeighborhoodResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Mahalle ekle
         * @description **Permission:** `settlement.neighborhood.create`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNeighborhoodCommand"];
                    "text/json": components["schemas"]["CreateNeighborhoodCommand"];
                    "application/*+json": components["schemas"]["CreateNeighborhoodCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NeighborhoodResponse"];
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                        "text/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/neighborhoods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mahalle getir
         * @description **Permission:** `settlement.neighborhood.view`
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NeighborhoodResponse"];
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                        "text/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        /**
         * Mahalle güncelle
         * @description **Permission:** `settlement.neighborhood.update`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNeighborhoodRequest"];
                    "text/json": components["schemas"]["UpdateNeighborhoodRequest"];
                    "application/*+json": components["schemas"]["UpdateNeighborhoodRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NeighborhoodResponse"];
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                        "text/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Mahalle sil
         * @description **Permission:** `settlement.neighborhood.delete`
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * İlleri listele
         * @description **Permission:** `settlement.province.list`
         */
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfProvinceResponse"];
                        "application/json": components["schemas"]["PagedResponseOfProvinceResponse"];
                        "text/json": components["schemas"]["PagedResponseOfProvinceResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * İl ekle
         * @description **Permission:** `settlement.province.create`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProvinceCommand"];
                    "text/json": components["schemas"]["CreateProvinceCommand"];
                    "application/*+json": components["schemas"]["CreateProvinceCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProvinceResponse"];
                        "application/json": components["schemas"]["ProvinceResponse"];
                        "text/json": components["schemas"]["ProvinceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/provinces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * İl getir
         * @description **Permission:** `settlement.province.view`
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProvinceResponse"];
                        "application/json": components["schemas"]["ProvinceResponse"];
                        "text/json": components["schemas"]["ProvinceResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateDistrictCommand: {
            name: string;
            /** Format: uuid */
            provinceId: string;
        };
        CreateNeighborhoodCommand: {
            name: string;
            /** Format: uuid */
            districtId: string;
            postalCode: null | string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            boundaryWkt: null | string;
        };
        CreateProvinceCommand: {
            name: string;
            /** Format: int32 */
            plateCode: number | string;
        };
        DistrictResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            provinceId: string;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        NeighborhoodResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            districtId: string;
            postalCode: null | string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            boundaryWkt: null | string;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        PagedResponseOfDistrictResponse: {
            items: components["schemas"]["DistrictResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        PagedResponseOfNeighborhoodResponse: {
            items: components["schemas"]["NeighborhoodResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        PagedResponseOfProvinceResponse: {
            items: components["schemas"]["ProvinceResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ProvinceResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            plateCode: number | string;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateNeighborhoodRequest: {
            name: string;
            postalCode: null | string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            boundaryWkt: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
