// AUTO-GENERATED by scripts/gen.mjs — do not edit. Regenerate with `pnpm gen`.
import type { Client, FetchOptions } from "openapi-fetch";
import type { paths } from "./schema";

/**
 * `settlement` modülü SDK'sı. Her metodun üzerinde gerekli **permission** JSDoc olarak yazılıdır.
 * Parametre/gövde/yanıt tipleri `schema.ts`'ten gelir (tam tipli).
 */
export function createSettlementSdk(client: Client<paths>) {
  return {
    /**
     * İlçe getir
     * @route GET /api/v1/settlement/districts/{id}
     * @permission settlement.district.view
     */
    getDistrictsById(init: FetchOptions<paths["/api/v1/settlement/districts/{id}"]["get"]>) {
      return client.GET("/api/v1/settlement/districts/{id}", init);
    },
    /**
     * İlçeleri listele
     * @route GET /api/v1/settlement/districts
     * @permission settlement.district.list
     */
    getDistricts(init?: FetchOptions<paths["/api/v1/settlement/districts"]["get"]>) {
      return client.GET("/api/v1/settlement/districts", init);
    },
    /**
     * İlçe ekle
     * @route POST /api/v1/settlement/districts
     * @permission settlement.district.create
     */
    postDistricts(init: FetchOptions<paths["/api/v1/settlement/districts"]["post"]>) {
      return client.POST("/api/v1/settlement/districts", init);
    },
    /**
     * Mahalle sil
     * @route DELETE /api/v1/settlement/neighborhoods/{id}
     * @permission settlement.neighborhood.delete
     */
    deleteNeighborhoodsById(init: FetchOptions<paths["/api/v1/settlement/neighborhoods/{id}"]["delete"]>) {
      return client.DELETE("/api/v1/settlement/neighborhoods/{id}", init);
    },
    /**
     * Mahalle getir
     * @route GET /api/v1/settlement/neighborhoods/{id}
     * @permission settlement.neighborhood.view
     */
    getNeighborhoodsById(init: FetchOptions<paths["/api/v1/settlement/neighborhoods/{id}"]["get"]>) {
      return client.GET("/api/v1/settlement/neighborhoods/{id}", init);
    },
    /**
     * Mahalle güncelle
     * @route PUT /api/v1/settlement/neighborhoods/{id}
     * @permission settlement.neighborhood.update
     */
    putNeighborhoodsById(init: FetchOptions<paths["/api/v1/settlement/neighborhoods/{id}"]["put"]>) {
      return client.PUT("/api/v1/settlement/neighborhoods/{id}", init);
    },
    /**
     * Mahalleleri listele
     * @route GET /api/v1/settlement/neighborhoods
     * @permission settlement.neighborhood.list
     */
    getNeighborhoods(init?: FetchOptions<paths["/api/v1/settlement/neighborhoods"]["get"]>) {
      return client.GET("/api/v1/settlement/neighborhoods", init);
    },
    /**
     * Mahalle ekle
     * @route POST /api/v1/settlement/neighborhoods
     * @permission settlement.neighborhood.create
     */
    postNeighborhoods(init: FetchOptions<paths["/api/v1/settlement/neighborhoods"]["post"]>) {
      return client.POST("/api/v1/settlement/neighborhoods", init);
    },
    /**
     * İl getir
     * @route GET /api/v1/settlement/provinces/{id}
     * @permission settlement.province.view
     */
    getProvincesById(init: FetchOptions<paths["/api/v1/settlement/provinces/{id}"]["get"]>) {
      return client.GET("/api/v1/settlement/provinces/{id}", init);
    },
    /**
     * İlleri listele
     * @route GET /api/v1/settlement/provinces
     * @permission settlement.province.list
     */
    getProvinces(init?: FetchOptions<paths["/api/v1/settlement/provinces"]["get"]>) {
      return client.GET("/api/v1/settlement/provinces", init);
    },
    /**
     * İl ekle
     * @route POST /api/v1/settlement/provinces
     * @permission settlement.province.create
     */
    postProvinces(init: FetchOptions<paths["/api/v1/settlement/provinces"]["post"]>) {
      return client.POST("/api/v1/settlement/provinces", init);
    },
  };
}
