// AUTO-GENERATED by scripts/gen.mjs — do not edit. Regenerate with `pnpm gen`.
import type { paths } from "./schema";
import { createApiClient, type ApiClientOptions } from "../../client";
import { createHesapSdk } from "./sdk";

/** Ham tipli openapi-fetch client (`hesap` modülü). */
export function createHesapClient(options: ApiClientOptions) {
  return createApiClient<paths>(options);
}

/** Adlandırılmış, permission-yorumlu SDK. */
export function createHesapApi(options: ApiClientOptions) {
  return createHesapSdk(createHesapClient(options));
}

export type { paths, components, operations } from "./schema";
export * from "./sdk";
export * from "./queries";
