// AUTO-GENERATED by scripts/gen.mjs — do not edit. Regenerate with `pnpm gen`.
import { useMutation, useQuery, useQueryClient, type UseMutationOptions, type UseQueryOptions } from "@tanstack/react-query";
import type { FetchOptions } from "openapi-fetch";
import type { paths } from "./schema";
import { createHesapSdk } from "./sdk";

type Sdk = ReturnType<typeof createHesapSdk>;
type Data<M extends keyof Sdk> = NonNullable<Awaited<ReturnType<Sdk[M]>>["data"]>;

/**
 * `hesap` modülü TanStack Query hook'ları (SDK üstünde cache + mutation yönetimi).
 * Her hook'un üzerinde gerekli **permission** JSDoc olarak yazılıdır. Bir kez `sdk` ile
 * kurun (web: configured client; RN: aynısı), dönen hook'ları bileşenlerde kullanın.
 */
export function createHesapQueries(sdk: Sdk) {
  return {
    /**
     * Giriş yap
     * @route POST /api/v1/hesap/auth/login
     * @permission (anonim — izin gerektirmez)
     */
    usePostAuthLogin(options?: Omit<UseMutationOptions<Data<"postAuthLogin">, Error, FetchOptions<paths["/api/v1/hesap/auth/login"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postAuthLogin">, Error, FetchOptions<paths["/api/v1/hesap/auth/login"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postAuthLogin(init);
          if (error) throw error as Error;
          return data as Data<"postAuthLogin">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/auth/login"),
          });
        },
        ...options,
      });
    },
    /**
     * Çıkış yap
     * @route POST /api/v1/hesap/auth/logout
     * @permission (anonim — izin gerektirmez)
     */
    usePostAuthLogout(options?: Omit<UseMutationOptions<Data<"postAuthLogout">, Error, FetchOptions<paths["/api/v1/hesap/auth/logout"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postAuthLogout">, Error, FetchOptions<paths["/api/v1/hesap/auth/logout"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postAuthLogout(init);
          if (error) throw error as Error;
          return data as Data<"postAuthLogout">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/auth/logout"),
          });
        },
        ...options,
      });
    },
    /**
     * Tokenı yenile
     * @route POST /api/v1/hesap/auth/refresh
     * @permission (anonim — izin gerektirmez)
     */
    usePostAuthRefresh(options?: Omit<UseMutationOptions<Data<"postAuthRefresh">, Error, FetchOptions<paths["/api/v1/hesap/auth/refresh"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postAuthRefresh">, Error, FetchOptions<paths["/api/v1/hesap/auth/refresh"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postAuthRefresh(init);
          if (error) throw error as Error;
          return data as Data<"postAuthRefresh">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/auth/refresh"),
          });
        },
        ...options,
      });
    },
    /**
     * Departman sil
     * @route DELETE /api/v1/hesap/departments/{id}
     * @permission hesap.department.delete
     */
    useDeleteDepartmentsById(options?: Omit<UseMutationOptions<Data<"deleteDepartmentsById">, Error, FetchOptions<paths["/api/v1/hesap/departments/{id}"]["delete"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"deleteDepartmentsById">, Error, FetchOptions<paths["/api/v1/hesap/departments/{id}"]["delete"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.deleteDepartmentsById(init);
          if (error) throw error as Error;
          return data as Data<"deleteDepartmentsById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/departments"),
          });
        },
        ...options,
      });
    },
    /**
     * Departman getir
     * @route GET /api/v1/hesap/departments/{id}
     * @permission hesap.department.view
     */
    useGetDepartmentsById(init: FetchOptions<paths["/api/v1/hesap/departments/{id}"]["get"]>, options?: Omit<UseQueryOptions<Data<"getDepartmentsById">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getDepartmentsById">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/departments/{id}", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getDepartmentsById(init);
          if (error) throw error as Error;
          return data as Data<"getDepartmentsById">;
        },
        ...options,
      });
    },
    /**
     * Departman güncelle
     * @route PUT /api/v1/hesap/departments/{id}
     * @permission hesap.department.update
     */
    usePutDepartmentsById(options?: Omit<UseMutationOptions<Data<"putDepartmentsById">, Error, FetchOptions<paths["/api/v1/hesap/departments/{id}"]["put"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"putDepartmentsById">, Error, FetchOptions<paths["/api/v1/hesap/departments/{id}"]["put"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.putDepartmentsById(init);
          if (error) throw error as Error;
          return data as Data<"putDepartmentsById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/departments"),
          });
        },
        ...options,
      });
    },
    /**
     * Departmanları listele
     * @route GET /api/v1/hesap/departments
     * @permission hesap.department.list
     */
    useGetDepartments(init?: FetchOptions<paths["/api/v1/hesap/departments"]["get"]>, options?: Omit<UseQueryOptions<Data<"getDepartments">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getDepartments">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/departments", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getDepartments(init);
          if (error) throw error as Error;
          return data as Data<"getDepartments">;
        },
        ...options,
      });
    },
    /**
     * Departman ekle
     * @route POST /api/v1/hesap/departments
     * @permission hesap.department.create
     */
    usePostDepartments(options?: Omit<UseMutationOptions<Data<"postDepartments">, Error, FetchOptions<paths["/api/v1/hesap/departments"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postDepartments">, Error, FetchOptions<paths["/api/v1/hesap/departments"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postDepartments(init);
          if (error) throw error as Error;
          return data as Data<"postDepartments">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/departments"),
          });
        },
        ...options,
      });
    },
    /**
     * Gruptan üye çıkar
     * @route DELETE /api/v1/hesap/groups/{id}/members/{userId}
     * @permission hesap.group.update
     */
    useDeleteGroupsByIdMembersByUserId(options?: Omit<UseMutationOptions<Data<"deleteGroupsByIdMembersByUserId">, Error, FetchOptions<paths["/api/v1/hesap/groups/{id}/members/{userId}"]["delete"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"deleteGroupsByIdMembersByUserId">, Error, FetchOptions<paths["/api/v1/hesap/groups/{id}/members/{userId}"]["delete"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.deleteGroupsByIdMembersByUserId(init);
          if (error) throw error as Error;
          return data as Data<"deleteGroupsByIdMembersByUserId">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/groups"),
          });
        },
        ...options,
      });
    },
    /**
     * Grup üyelerini listele
     * @route GET /api/v1/hesap/groups/{id}/members
     * @permission hesap.group.view
     */
    useGetGroupsByIdMembers(init: FetchOptions<paths["/api/v1/hesap/groups/{id}/members"]["get"]>, options?: Omit<UseQueryOptions<Data<"getGroupsByIdMembers">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getGroupsByIdMembers">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/groups/{id}/members", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getGroupsByIdMembers(init);
          if (error) throw error as Error;
          return data as Data<"getGroupsByIdMembers">;
        },
        ...options,
      });
    },
    /**
     * Gruba üye ekle
     * @route POST /api/v1/hesap/groups/{id}/members
     * @permission hesap.group.update
     */
    usePostGroupsByIdMembers(options?: Omit<UseMutationOptions<Data<"postGroupsByIdMembers">, Error, FetchOptions<paths["/api/v1/hesap/groups/{id}/members"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postGroupsByIdMembers">, Error, FetchOptions<paths["/api/v1/hesap/groups/{id}/members"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postGroupsByIdMembers(init);
          if (error) throw error as Error;
          return data as Data<"postGroupsByIdMembers">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/groups"),
          });
        },
        ...options,
      });
    },
    /**
     * Grup sil
     * @route DELETE /api/v1/hesap/groups/{id}
     * @permission hesap.group.delete
     */
    useDeleteGroupsById(options?: Omit<UseMutationOptions<Data<"deleteGroupsById">, Error, FetchOptions<paths["/api/v1/hesap/groups/{id}"]["delete"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"deleteGroupsById">, Error, FetchOptions<paths["/api/v1/hesap/groups/{id}"]["delete"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.deleteGroupsById(init);
          if (error) throw error as Error;
          return data as Data<"deleteGroupsById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/groups"),
          });
        },
        ...options,
      });
    },
    /**
     * Grup getir
     * @route GET /api/v1/hesap/groups/{id}
     * @permission hesap.group.view
     */
    useGetGroupsById(init: FetchOptions<paths["/api/v1/hesap/groups/{id}"]["get"]>, options?: Omit<UseQueryOptions<Data<"getGroupsById">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getGroupsById">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/groups/{id}", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getGroupsById(init);
          if (error) throw error as Error;
          return data as Data<"getGroupsById">;
        },
        ...options,
      });
    },
    /**
     * Grup güncelle
     * @route PUT /api/v1/hesap/groups/{id}
     * @permission hesap.group.update
     */
    usePutGroupsById(options?: Omit<UseMutationOptions<Data<"putGroupsById">, Error, FetchOptions<paths["/api/v1/hesap/groups/{id}"]["put"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"putGroupsById">, Error, FetchOptions<paths["/api/v1/hesap/groups/{id}"]["put"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.putGroupsById(init);
          if (error) throw error as Error;
          return data as Data<"putGroupsById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/groups"),
          });
        },
        ...options,
      });
    },
    /**
     * Grupları listele
     * @route GET /api/v1/hesap/groups
     * @permission hesap.group.list
     */
    useGetGroups(init?: FetchOptions<paths["/api/v1/hesap/groups"]["get"]>, options?: Omit<UseQueryOptions<Data<"getGroups">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getGroups">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/groups", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getGroups(init);
          if (error) throw error as Error;
          return data as Data<"getGroups">;
        },
        ...options,
      });
    },
    /**
     * Grup ekle
     * @route POST /api/v1/hesap/groups
     * @permission hesap.group.create
     */
    usePostGroups(options?: Omit<UseMutationOptions<Data<"postGroups">, Error, FetchOptions<paths["/api/v1/hesap/groups"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postGroups">, Error, FetchOptions<paths["/api/v1/hesap/groups"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postGroups(init);
          if (error) throw error as Error;
          return data as Data<"postGroups">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/groups"),
          });
        },
        ...options,
      });
    },
    /**
     * Beni göster
     * @route GET /api/v1/hesap/me
     * @permission (anonim — izin gerektirmez)
     */
    useGetMe(init?: FetchOptions<paths["/api/v1/hesap/me"]["get"]>, options?: Omit<UseQueryOptions<Data<"getMe">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getMe">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/me", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getMe(init);
          if (error) throw error as Error;
          return data as Data<"getMe">;
        },
        ...options,
      });
    },
    /**
     * Yetkileri listele
     * @route GET /api/v1/hesap/permissions
     * @permission hesap.permission.list
     */
    useGetPermissions(init?: FetchOptions<paths["/api/v1/hesap/permissions"]["get"]>, options?: Omit<UseQueryOptions<Data<"getPermissions">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getPermissions">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/permissions", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getPermissions(init);
          if (error) throw error as Error;
          return data as Data<"getPermissions">;
        },
        ...options,
      });
    },
    /**
     * Erişim politikası sil
     * @route DELETE /api/v1/hesap/policies/{id}
     * @permission hesap.policy.delete
     */
    useDeletePoliciesById(options?: Omit<UseMutationOptions<Data<"deletePoliciesById">, Error, FetchOptions<paths["/api/v1/hesap/policies/{id}"]["delete"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"deletePoliciesById">, Error, FetchOptions<paths["/api/v1/hesap/policies/{id}"]["delete"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.deletePoliciesById(init);
          if (error) throw error as Error;
          return data as Data<"deletePoliciesById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/policies"),
          });
        },
        ...options,
      });
    },
    /**
     * Erişim politikalarını listele
     * @route GET /api/v1/hesap/policies
     * @permission hesap.policy.list
     */
    useGetPolicies(init?: FetchOptions<paths["/api/v1/hesap/policies"]["get"]>, options?: Omit<UseQueryOptions<Data<"getPolicies">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getPolicies">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/policies", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getPolicies(init);
          if (error) throw error as Error;
          return data as Data<"getPolicies">;
        },
        ...options,
      });
    },
    /**
     * Erişim politikası ekle
     * @route POST /api/v1/hesap/policies
     * @permission hesap.policy.create
     */
    usePostPolicies(options?: Omit<UseMutationOptions<Data<"postPolicies">, Error, FetchOptions<paths["/api/v1/hesap/policies"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postPolicies">, Error, FetchOptions<paths["/api/v1/hesap/policies"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postPolicies(init);
          if (error) throw error as Error;
          return data as Data<"postPolicies">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/policies"),
          });
        },
        ...options,
      });
    },
    /**
     * Role yetki ata
     * @route PUT /api/v1/hesap/roles/{id}/permissions
     * @permission hesap.role.assignpermissions
     */
    usePutRolesByIdPermissions(options?: Omit<UseMutationOptions<Data<"putRolesByIdPermissions">, Error, FetchOptions<paths["/api/v1/hesap/roles/{id}/permissions"]["put"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"putRolesByIdPermissions">, Error, FetchOptions<paths["/api/v1/hesap/roles/{id}/permissions"]["put"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.putRolesByIdPermissions(init);
          if (error) throw error as Error;
          return data as Data<"putRolesByIdPermissions">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/roles"),
          });
        },
        ...options,
      });
    },
    /**
     * Rol sil
     * @route DELETE /api/v1/hesap/roles/{id}
     * @permission hesap.role.delete
     */
    useDeleteRolesById(options?: Omit<UseMutationOptions<Data<"deleteRolesById">, Error, FetchOptions<paths["/api/v1/hesap/roles/{id}"]["delete"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"deleteRolesById">, Error, FetchOptions<paths["/api/v1/hesap/roles/{id}"]["delete"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.deleteRolesById(init);
          if (error) throw error as Error;
          return data as Data<"deleteRolesById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/roles"),
          });
        },
        ...options,
      });
    },
    /**
     * Rol getir
     * @route GET /api/v1/hesap/roles/{id}
     * @permission hesap.role.view
     */
    useGetRolesById(init: FetchOptions<paths["/api/v1/hesap/roles/{id}"]["get"]>, options?: Omit<UseQueryOptions<Data<"getRolesById">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getRolesById">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/roles/{id}", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getRolesById(init);
          if (error) throw error as Error;
          return data as Data<"getRolesById">;
        },
        ...options,
      });
    },
    /**
     * Rol güncelle
     * @route PUT /api/v1/hesap/roles/{id}
     * @permission hesap.role.update
     */
    usePutRolesById(options?: Omit<UseMutationOptions<Data<"putRolesById">, Error, FetchOptions<paths["/api/v1/hesap/roles/{id}"]["put"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"putRolesById">, Error, FetchOptions<paths["/api/v1/hesap/roles/{id}"]["put"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.putRolesById(init);
          if (error) throw error as Error;
          return data as Data<"putRolesById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/roles"),
          });
        },
        ...options,
      });
    },
    /**
     * Rolleri listele
     * @route GET /api/v1/hesap/roles
     * @permission hesap.role.list
     */
    useGetRoles(init?: FetchOptions<paths["/api/v1/hesap/roles"]["get"]>, options?: Omit<UseQueryOptions<Data<"getRoles">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getRoles">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/roles", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getRoles(init);
          if (error) throw error as Error;
          return data as Data<"getRoles">;
        },
        ...options,
      });
    },
    /**
     * Rol ekle
     * @route POST /api/v1/hesap/roles
     * @permission hesap.role.create
     */
    usePostRoles(options?: Omit<UseMutationOptions<Data<"postRoles">, Error, FetchOptions<paths["/api/v1/hesap/roles"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postRoles">, Error, FetchOptions<paths["/api/v1/hesap/roles"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postRoles(init);
          if (error) throw error as Error;
          return data as Data<"postRoles">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/roles"),
          });
        },
        ...options,
      });
    },
    /**
     * Kullanıcının departmanlarını ayarla
     * @route PUT /api/v1/hesap/users/{id}/departments
     * @permission hesap.user.update
     */
    usePutUsersByIdDepartments(options?: Omit<UseMutationOptions<Data<"putUsersByIdDepartments">, Error, FetchOptions<paths["/api/v1/hesap/users/{id}/departments"]["put"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"putUsersByIdDepartments">, Error, FetchOptions<paths["/api/v1/hesap/users/{id}/departments"]["put"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.putUsersByIdDepartments(init);
          if (error) throw error as Error;
          return data as Data<"putUsersByIdDepartments">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/users"),
          });
        },
        ...options,
      });
    },
    /**
     * Kullanıcıya rol ata
     * @route PUT /api/v1/hesap/users/{id}/roles
     * @permission hesap.user.assignroles
     */
    usePutUsersByIdRoles(options?: Omit<UseMutationOptions<Data<"putUsersByIdRoles">, Error, FetchOptions<paths["/api/v1/hesap/users/{id}/roles"]["put"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"putUsersByIdRoles">, Error, FetchOptions<paths["/api/v1/hesap/users/{id}/roles"]["put"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.putUsersByIdRoles(init);
          if (error) throw error as Error;
          return data as Data<"putUsersByIdRoles">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/users"),
          });
        },
        ...options,
      });
    },
    /**
     * Kullanıcı sil
     * @route DELETE /api/v1/hesap/users/{id}
     * @permission hesap.user.delete
     */
    useDeleteUsersById(options?: Omit<UseMutationOptions<Data<"deleteUsersById">, Error, FetchOptions<paths["/api/v1/hesap/users/{id}"]["delete"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"deleteUsersById">, Error, FetchOptions<paths["/api/v1/hesap/users/{id}"]["delete"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.deleteUsersById(init);
          if (error) throw error as Error;
          return data as Data<"deleteUsersById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/users"),
          });
        },
        ...options,
      });
    },
    /**
     * Kullanıcı getir
     * @route GET /api/v1/hesap/users/{id}
     * @permission hesap.user.view
     */
    useGetUsersById(init: FetchOptions<paths["/api/v1/hesap/users/{id}"]["get"]>, options?: Omit<UseQueryOptions<Data<"getUsersById">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getUsersById">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/users/{id}", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getUsersById(init);
          if (error) throw error as Error;
          return data as Data<"getUsersById">;
        },
        ...options,
      });
    },
    /**
     * Kullanıcı güncelle
     * @route PUT /api/v1/hesap/users/{id}
     * @permission hesap.user.update
     */
    usePutUsersById(options?: Omit<UseMutationOptions<Data<"putUsersById">, Error, FetchOptions<paths["/api/v1/hesap/users/{id}"]["put"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"putUsersById">, Error, FetchOptions<paths["/api/v1/hesap/users/{id}"]["put"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.putUsersById(init);
          if (error) throw error as Error;
          return data as Data<"putUsersById">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/users"),
          });
        },
        ...options,
      });
    },
    /**
     * Kullanıcıları listele
     * @route GET /api/v1/hesap/users
     * @permission hesap.user.list
     */
    useGetUsers(init?: FetchOptions<paths["/api/v1/hesap/users"]["get"]>, options?: Omit<UseQueryOptions<Data<"getUsers">, Error>, "queryKey" | "queryFn">) {
      return useQuery<Data<"getUsers">, Error>({
        queryKey: ["hesap", "/api/v1/hesap/users", init?.params ?? {}],
        queryFn: async () => {
          const { data, error } = await sdk.getUsers(init);
          if (error) throw error as Error;
          return data as Data<"getUsers">;
        },
        ...options,
      });
    },
    /**
     * Kullanıcı ekle
     * @route POST /api/v1/hesap/users
     * @permission hesap.user.create
     */
    usePostUsers(options?: Omit<UseMutationOptions<Data<"postUsers">, Error, FetchOptions<paths["/api/v1/hesap/users"]["post"]>>, "mutationFn">) {
      const queryClient = useQueryClient();
      return useMutation<Data<"postUsers">, Error, FetchOptions<paths["/api/v1/hesap/users"]["post"]>>({
        mutationFn: async (init) => {
          const { data, error } = await sdk.postUsers(init);
          if (error) throw error as Error;
          return data as Data<"postUsers">;
        },
        // Mutasyon sonrası ilgili kaynağın query'lerini tazele. options.onSuccess verirsen
        // bu davranışı sen üstlenirsin (aşağıdaki spread onu ezer).
        onSuccess: () => {
          void queryClient.invalidateQueries({
            predicate: (q) =>
              Array.isArray(q.queryKey) &&
              q.queryKey[0] === "hesap" &&
              typeof q.queryKey[1] === "string" &&
              (q.queryKey[1] as string).startsWith("/api/v1/hesap/users"),
          });
        },
        ...options,
      });
    },
  };
}
