/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/hesap/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Giriş yap */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResponse"];
                        "application/json": components["schemas"]["TokenResponse"];
                        "text/json": components["schemas"]["TokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tokenı yenile */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                    "text/json": components["schemas"]["RefreshRequest"];
                    "application/*+json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TokenResponse"];
                        "application/json": components["schemas"]["TokenResponse"];
                        "text/json": components["schemas"]["TokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Çıkış yap */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                    "text/json": components["schemas"]["LogoutRequest"];
                    "application/*+json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Departmanları listele
         * @description **Permission:** `hesap.department.list`
         */
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfDepartmentResponse"];
                        "application/json": components["schemas"]["PagedResponseOfDepartmentResponse"];
                        "text/json": components["schemas"]["PagedResponseOfDepartmentResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Departman ekle
         * @description **Permission:** `hesap.department.create`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDepartmentCommand"];
                    "text/json": components["schemas"]["CreateDepartmentCommand"];
                    "application/*+json": components["schemas"]["CreateDepartmentCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponse"];
                        "application/json": components["schemas"]["DepartmentResponse"];
                        "text/json": components["schemas"]["DepartmentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Departman getir
         * @description **Permission:** `hesap.department.view`
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponse"];
                        "application/json": components["schemas"]["DepartmentResponse"];
                        "text/json": components["schemas"]["DepartmentResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        /**
         * Departman güncelle
         * @description **Permission:** `hesap.department.update`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDepartmentRequest"];
                    "text/json": components["schemas"]["UpdateDepartmentRequest"];
                    "application/*+json": components["schemas"]["UpdateDepartmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponse"];
                        "application/json": components["schemas"]["DepartmentResponse"];
                        "text/json": components["schemas"]["DepartmentResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Departman sil
         * @description **Permission:** `hesap.department.delete`
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grupları listele
         * @description **Permission:** `hesap.group.list`
         */
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfGroupResponse"];
                        "application/json": components["schemas"]["PagedResponseOfGroupResponse"];
                        "text/json": components["schemas"]["PagedResponseOfGroupResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Grup ekle
         * @description **Permission:** `hesap.group.create`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateGroupCommand"];
                    "text/json": components["schemas"]["CreateGroupCommand"];
                    "application/*+json": components["schemas"]["CreateGroupCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GroupResponse"];
                        "application/json": components["schemas"]["GroupResponse"];
                        "text/json": components["schemas"]["GroupResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grup getir
         * @description **Permission:** `hesap.group.view`
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GroupResponse"];
                        "application/json": components["schemas"]["GroupResponse"];
                        "text/json": components["schemas"]["GroupResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        /**
         * Grup güncelle
         * @description **Permission:** `hesap.group.update`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateGroupRequest"];
                    "text/json": components["schemas"]["UpdateGroupRequest"];
                    "application/*+json": components["schemas"]["UpdateGroupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GroupResponse"];
                        "application/json": components["schemas"]["GroupResponse"];
                        "text/json": components["schemas"]["GroupResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Grup sil
         * @description **Permission:** `hesap.group.delete`
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/groups/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grup üyelerini listele
         * @description **Permission:** `hesap.group.view`
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GroupMemberResponse"][];
                        "application/json": components["schemas"]["GroupMemberResponse"][];
                        "text/json": components["schemas"]["GroupMemberResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Gruba üye ekle
         * @description **Permission:** `hesap.group.update`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GroupMemberRequest"];
                    "text/json": components["schemas"]["GroupMemberRequest"];
                    "application/*+json": components["schemas"]["GroupMemberRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/groups/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Gruptan üye çıkar
         * @description **Permission:** `hesap.group.update`
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Beni göster */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserResponse"];
                        "application/json": components["schemas"]["CurrentUserResponse"];
                        "text/json": components["schemas"]["CurrentUserResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yetkileri listele
         * @description **Permission:** `hesap.permission.list`
         */
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfPermissionResponse"];
                        "application/json": components["schemas"]["PagedResponseOfPermissionResponse"];
                        "text/json": components["schemas"]["PagedResponseOfPermissionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Erişim politikalarını listele
         * @description **Permission:** `hesap.policy.list`
         */
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfPolicyResponse"];
                        "application/json": components["schemas"]["PagedResponseOfPolicyResponse"];
                        "text/json": components["schemas"]["PagedResponseOfPolicyResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Erişim politikası ekle
         * @description **Permission:** `hesap.policy.create`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePolicyCommand"];
                    "text/json": components["schemas"]["CreatePolicyCommand"];
                    "application/*+json": components["schemas"]["CreatePolicyCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PolicyResponse"];
                        "application/json": components["schemas"]["PolicyResponse"];
                        "text/json": components["schemas"]["PolicyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Erişim politikası sil
         * @description **Permission:** `hesap.policy.delete`
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rolleri listele
         * @description **Permission:** `hesap.role.list`
         */
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfRoleResponse"];
                        "application/json": components["schemas"]["PagedResponseOfRoleResponse"];
                        "text/json": components["schemas"]["PagedResponseOfRoleResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Rol ekle
         * @description **Permission:** `hesap.role.create`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRoleCommand"];
                    "text/json": components["schemas"]["CreateRoleCommand"];
                    "application/*+json": components["schemas"]["CreateRoleCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleResponse"];
                        "application/json": components["schemas"]["RoleResponse"];
                        "text/json": components["schemas"]["RoleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rol getir
         * @description **Permission:** `hesap.role.view`
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleDetailResponse"];
                        "application/json": components["schemas"]["RoleDetailResponse"];
                        "text/json": components["schemas"]["RoleDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        /**
         * Rol güncelle
         * @description **Permission:** `hesap.role.update`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRoleRequest"];
                    "text/json": components["schemas"]["UpdateRoleRequest"];
                    "application/*+json": components["schemas"]["UpdateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleResponse"];
                        "application/json": components["schemas"]["RoleResponse"];
                        "text/json": components["schemas"]["RoleResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Rol sil
         * @description **Permission:** `hesap.role.delete`
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/roles/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Role yetki ata
         * @description **Permission:** `hesap.role.assignpermissions`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignRolePermissionsRequest"];
                    "text/json": components["schemas"]["AssignRolePermissionsRequest"];
                    "application/*+json": components["schemas"]["AssignRolePermissionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleDetailResponse"];
                        "application/json": components["schemas"]["RoleDetailResponse"];
                        "text/json": components["schemas"]["RoleDetailResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kullanıcıları listele
         * @description **Permission:** `hesap.user.list`
         */
        get: {
            parameters: {
                query?: {
                    Page?: number | string;
                    PageSize?: number | string;
                    Sort?: string;
                    Search?: string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfUserResponse"];
                        "application/json": components["schemas"]["PagedResponseOfUserResponse"];
                        "text/json": components["schemas"]["PagedResponseOfUserResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Kullanıcı ekle
         * @description **Permission:** `hesap.user.create`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserCommand"];
                    "text/json": components["schemas"]["CreateUserCommand"];
                    "application/*+json": components["schemas"]["CreateUserCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponse"];
                        "application/json": components["schemas"]["UserResponse"];
                        "text/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kullanıcı getir
         * @description **Permission:** `hesap.user.view`
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDetailResponse"];
                        "application/json": components["schemas"]["UserDetailResponse"];
                        "text/json": components["schemas"]["UserDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        /**
         * Kullanıcı güncelle
         * @description **Permission:** `hesap.user.update`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponse"];
                        "application/json": components["schemas"]["UserResponse"];
                        "text/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Kullanıcı sil
         * @description **Permission:** `hesap.user.delete`
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Kullanıcıya rol ata
         * @description **Permission:** `hesap.user.assignroles`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignUserRolesRequest"];
                    "text/json": components["schemas"]["AssignUserRolesRequest"];
                    "application/*+json": components["schemas"]["AssignUserRolesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDetailResponse"];
                        "application/json": components["schemas"]["UserDetailResponse"];
                        "text/json": components["schemas"]["UserDetailResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hesap/users/{id}/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Kullanıcının departmanlarını ayarla
         * @description **Permission:** `hesap.user.update`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetUserDepartmentsRequest"];
                    "text/json": components["schemas"]["SetUserDepartmentsRequest"];
                    "application/*+json": components["schemas"]["SetUserDepartmentsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDetailResponse"];
                        "application/json": components["schemas"]["UserDetailResponse"];
                        "text/json": components["schemas"]["UserDetailResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssignRolePermissionsRequest: {
            permissionKeys: string[];
        };
        AssignUserRolesRequest: {
            roles: string[];
        };
        CreateDepartmentCommand: {
            name: string;
            /** Format: uuid */
            parentId: null | string;
        };
        CreateGroupCommand: {
            name: string;
            description: null | string;
        };
        CreatePolicyCommand: {
            subjectType: components["schemas"]["PolicySubjectType"];
            /** Format: uuid */
            subjectId: string;
            kind: components["schemas"]["PolicyKind"];
            effect: components["schemas"]["PolicyEffect"];
            value: string;
            /** Format: int32 */
            priority: number | string;
        };
        CreateRoleCommand: {
            name: string;
            description: null | string;
        };
        CreateUserCommand: {
            userName: string;
            email: string;
            displayName: null | string;
            password: string;
            roles: null | string[];
        };
        CurrentUserResponse: {
            userId: null | string;
            userName: null | string;
            roles: string[];
            permissions: {
                [key: string]: string[];
            };
        };
        DepartmentResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            parentId: null | string;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        GroupMemberRequest: {
            /** Format: uuid */
            userId: string;
        };
        GroupMemberResponse: {
            /** Format: uuid */
            userId: string;
            userName: string;
            displayName: null | string;
        };
        GroupResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
            /** Format: int32 */
            memberCount: number | string;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        LoginRequest: {
            userName: string;
            password: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        PagedResponseOfDepartmentResponse: {
            items: components["schemas"]["DepartmentResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        PagedResponseOfGroupResponse: {
            items: components["schemas"]["GroupResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        PagedResponseOfPermissionResponse: {
            items: components["schemas"]["PermissionResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        PagedResponseOfPolicyResponse: {
            items: components["schemas"]["PolicyResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        PagedResponseOfRoleResponse: {
            items: components["schemas"]["RoleResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        PagedResponseOfUserResponse: {
            items: components["schemas"]["UserResponse"][];
            /** Format: int64 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
        };
        PermissionResponse: {
            /** Format: uuid */
            id: string;
            key: string;
            module: string;
            resource: string;
            action: string;
            title: string;
            description: null | string;
        };
        PolicyEffect: number;
        PolicyKind: number;
        PolicyResponse: {
            /** Format: uuid */
            id: string;
            subjectType: components["schemas"]["PolicySubjectType"];
            /** Format: uuid */
            subjectId: string;
            kind: components["schemas"]["PolicyKind"];
            effect: components["schemas"]["PolicyEffect"];
            value: string;
            /** Format: int32 */
            priority: number | string;
        };
        PolicySubjectType: number;
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RoleDetailResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
            permissions: string[];
            /** Format: date-time */
            createdAt: string;
        };
        RoleResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
            /** Format: int32 */
            permissionCount: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        SetUserDepartmentsRequest: {
            departmentIds: string[];
        };
        TokenResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
        };
        UpdateDepartmentRequest: {
            name: string;
            /** Format: uuid */
            parentId: null | string;
        };
        UpdateGroupRequest: {
            name: string;
            description: null | string;
        };
        UpdateRoleRequest: {
            name: string;
            description: null | string;
        };
        UpdateUserRequest: {
            email: null | string;
            displayName: null | string;
            lockoutEnabled: boolean;
        };
        UserDetailResponse: {
            /** Format: uuid */
            id: string;
            userName: string;
            email: null | string;
            displayName: null | string;
            lockoutEnabled: boolean;
            roles: string[];
            departments: string[];
            /** Format: date-time */
            createdAt: string;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            userName: string;
            email: null | string;
            displayName: null | string;
            lockoutEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
