// AUTO-GENERATED by scripts/gen.mjs — do not edit. Regenerate with `pnpm gen`.
import type { Client, FetchOptions } from "openapi-fetch";
import type { paths } from "./schema";

/**
 * `hesap` modülü SDK'sı. Her metodun üzerinde gerekli **permission** JSDoc olarak yazılıdır.
 * Parametre/gövde/yanıt tipleri `schema.ts`'ten gelir (tam tipli).
 */
export function createHesapSdk(client: Client<paths>) {
  return {
    /**
     * Giriş yap
     * @route POST /api/v1/hesap/auth/login
     * @permission (anonim — izin gerektirmez)
     */
    postAuthLogin(init: FetchOptions<paths["/api/v1/hesap/auth/login"]["post"]>) {
      return client.POST("/api/v1/hesap/auth/login", init);
    },
    /**
     * Çıkış yap
     * @route POST /api/v1/hesap/auth/logout
     * @permission (anonim — izin gerektirmez)
     */
    postAuthLogout(init: FetchOptions<paths["/api/v1/hesap/auth/logout"]["post"]>) {
      return client.POST("/api/v1/hesap/auth/logout", init);
    },
    /**
     * Tokenı yenile
     * @route POST /api/v1/hesap/auth/refresh
     * @permission (anonim — izin gerektirmez)
     */
    postAuthRefresh(init: FetchOptions<paths["/api/v1/hesap/auth/refresh"]["post"]>) {
      return client.POST("/api/v1/hesap/auth/refresh", init);
    },
    /**
     * Departman sil
     * @route DELETE /api/v1/hesap/departments/{id}
     * @permission hesap.department.delete
     */
    deleteDepartmentsById(init: FetchOptions<paths["/api/v1/hesap/departments/{id}"]["delete"]>) {
      return client.DELETE("/api/v1/hesap/departments/{id}", init);
    },
    /**
     * Departman getir
     * @route GET /api/v1/hesap/departments/{id}
     * @permission hesap.department.view
     */
    getDepartmentsById(init: FetchOptions<paths["/api/v1/hesap/departments/{id}"]["get"]>) {
      return client.GET("/api/v1/hesap/departments/{id}", init);
    },
    /**
     * Departman güncelle
     * @route PUT /api/v1/hesap/departments/{id}
     * @permission hesap.department.update
     */
    putDepartmentsById(init: FetchOptions<paths["/api/v1/hesap/departments/{id}"]["put"]>) {
      return client.PUT("/api/v1/hesap/departments/{id}", init);
    },
    /**
     * Departmanları listele
     * @route GET /api/v1/hesap/departments
     * @permission hesap.department.list
     */
    getDepartments(init?: FetchOptions<paths["/api/v1/hesap/departments"]["get"]>) {
      return client.GET("/api/v1/hesap/departments", init);
    },
    /**
     * Departman ekle
     * @route POST /api/v1/hesap/departments
     * @permission hesap.department.create
     */
    postDepartments(init: FetchOptions<paths["/api/v1/hesap/departments"]["post"]>) {
      return client.POST("/api/v1/hesap/departments", init);
    },
    /**
     * Gruptan üye çıkar
     * @route DELETE /api/v1/hesap/groups/{id}/members/{userId}
     * @permission hesap.group.update
     */
    deleteGroupsByIdMembersByUserId(init: FetchOptions<paths["/api/v1/hesap/groups/{id}/members/{userId}"]["delete"]>) {
      return client.DELETE("/api/v1/hesap/groups/{id}/members/{userId}", init);
    },
    /**
     * Grup üyelerini listele
     * @route GET /api/v1/hesap/groups/{id}/members
     * @permission hesap.group.view
     */
    getGroupsByIdMembers(init: FetchOptions<paths["/api/v1/hesap/groups/{id}/members"]["get"]>) {
      return client.GET("/api/v1/hesap/groups/{id}/members", init);
    },
    /**
     * Gruba üye ekle
     * @route POST /api/v1/hesap/groups/{id}/members
     * @permission hesap.group.update
     */
    postGroupsByIdMembers(init: FetchOptions<paths["/api/v1/hesap/groups/{id}/members"]["post"]>) {
      return client.POST("/api/v1/hesap/groups/{id}/members", init);
    },
    /**
     * Grup sil
     * @route DELETE /api/v1/hesap/groups/{id}
     * @permission hesap.group.delete
     */
    deleteGroupsById(init: FetchOptions<paths["/api/v1/hesap/groups/{id}"]["delete"]>) {
      return client.DELETE("/api/v1/hesap/groups/{id}", init);
    },
    /**
     * Grup getir
     * @route GET /api/v1/hesap/groups/{id}
     * @permission hesap.group.view
     */
    getGroupsById(init: FetchOptions<paths["/api/v1/hesap/groups/{id}"]["get"]>) {
      return client.GET("/api/v1/hesap/groups/{id}", init);
    },
    /**
     * Grup güncelle
     * @route PUT /api/v1/hesap/groups/{id}
     * @permission hesap.group.update
     */
    putGroupsById(init: FetchOptions<paths["/api/v1/hesap/groups/{id}"]["put"]>) {
      return client.PUT("/api/v1/hesap/groups/{id}", init);
    },
    /**
     * Grupları listele
     * @route GET /api/v1/hesap/groups
     * @permission hesap.group.list
     */
    getGroups(init?: FetchOptions<paths["/api/v1/hesap/groups"]["get"]>) {
      return client.GET("/api/v1/hesap/groups", init);
    },
    /**
     * Grup ekle
     * @route POST /api/v1/hesap/groups
     * @permission hesap.group.create
     */
    postGroups(init: FetchOptions<paths["/api/v1/hesap/groups"]["post"]>) {
      return client.POST("/api/v1/hesap/groups", init);
    },
    /**
     * Beni göster
     * @route GET /api/v1/hesap/me
     * @permission (anonim — izin gerektirmez)
     */
    getMe(init?: FetchOptions<paths["/api/v1/hesap/me"]["get"]>) {
      return client.GET("/api/v1/hesap/me", init);
    },
    /**
     * Yetkileri listele
     * @route GET /api/v1/hesap/permissions
     * @permission hesap.permission.list
     */
    getPermissions(init?: FetchOptions<paths["/api/v1/hesap/permissions"]["get"]>) {
      return client.GET("/api/v1/hesap/permissions", init);
    },
    /**
     * Erişim politikası sil
     * @route DELETE /api/v1/hesap/policies/{id}
     * @permission hesap.policy.delete
     */
    deletePoliciesById(init: FetchOptions<paths["/api/v1/hesap/policies/{id}"]["delete"]>) {
      return client.DELETE("/api/v1/hesap/policies/{id}", init);
    },
    /**
     * Erişim politikalarını listele
     * @route GET /api/v1/hesap/policies
     * @permission hesap.policy.list
     */
    getPolicies(init?: FetchOptions<paths["/api/v1/hesap/policies"]["get"]>) {
      return client.GET("/api/v1/hesap/policies", init);
    },
    /**
     * Erişim politikası ekle
     * @route POST /api/v1/hesap/policies
     * @permission hesap.policy.create
     */
    postPolicies(init: FetchOptions<paths["/api/v1/hesap/policies"]["post"]>) {
      return client.POST("/api/v1/hesap/policies", init);
    },
    /**
     * Role yetki ata
     * @route PUT /api/v1/hesap/roles/{id}/permissions
     * @permission hesap.role.assignpermissions
     */
    putRolesByIdPermissions(init: FetchOptions<paths["/api/v1/hesap/roles/{id}/permissions"]["put"]>) {
      return client.PUT("/api/v1/hesap/roles/{id}/permissions", init);
    },
    /**
     * Rol sil
     * @route DELETE /api/v1/hesap/roles/{id}
     * @permission hesap.role.delete
     */
    deleteRolesById(init: FetchOptions<paths["/api/v1/hesap/roles/{id}"]["delete"]>) {
      return client.DELETE("/api/v1/hesap/roles/{id}", init);
    },
    /**
     * Rol getir
     * @route GET /api/v1/hesap/roles/{id}
     * @permission hesap.role.view
     */
    getRolesById(init: FetchOptions<paths["/api/v1/hesap/roles/{id}"]["get"]>) {
      return client.GET("/api/v1/hesap/roles/{id}", init);
    },
    /**
     * Rol güncelle
     * @route PUT /api/v1/hesap/roles/{id}
     * @permission hesap.role.update
     */
    putRolesById(init: FetchOptions<paths["/api/v1/hesap/roles/{id}"]["put"]>) {
      return client.PUT("/api/v1/hesap/roles/{id}", init);
    },
    /**
     * Rolleri listele
     * @route GET /api/v1/hesap/roles
     * @permission hesap.role.list
     */
    getRoles(init?: FetchOptions<paths["/api/v1/hesap/roles"]["get"]>) {
      return client.GET("/api/v1/hesap/roles", init);
    },
    /**
     * Rol ekle
     * @route POST /api/v1/hesap/roles
     * @permission hesap.role.create
     */
    postRoles(init: FetchOptions<paths["/api/v1/hesap/roles"]["post"]>) {
      return client.POST("/api/v1/hesap/roles", init);
    },
    /**
     * Kullanıcının departmanlarını ayarla
     * @route PUT /api/v1/hesap/users/{id}/departments
     * @permission hesap.user.update
     */
    putUsersByIdDepartments(init: FetchOptions<paths["/api/v1/hesap/users/{id}/departments"]["put"]>) {
      return client.PUT("/api/v1/hesap/users/{id}/departments", init);
    },
    /**
     * Kullanıcıya rol ata
     * @route PUT /api/v1/hesap/users/{id}/roles
     * @permission hesap.user.assignroles
     */
    putUsersByIdRoles(init: FetchOptions<paths["/api/v1/hesap/users/{id}/roles"]["put"]>) {
      return client.PUT("/api/v1/hesap/users/{id}/roles", init);
    },
    /**
     * Kullanıcı sil
     * @route DELETE /api/v1/hesap/users/{id}
     * @permission hesap.user.delete
     */
    deleteUsersById(init: FetchOptions<paths["/api/v1/hesap/users/{id}"]["delete"]>) {
      return client.DELETE("/api/v1/hesap/users/{id}", init);
    },
    /**
     * Kullanıcı getir
     * @route GET /api/v1/hesap/users/{id}
     * @permission hesap.user.view
     */
    getUsersById(init: FetchOptions<paths["/api/v1/hesap/users/{id}"]["get"]>) {
      return client.GET("/api/v1/hesap/users/{id}", init);
    },
    /**
     * Kullanıcı güncelle
     * @route PUT /api/v1/hesap/users/{id}
     * @permission hesap.user.update
     */
    putUsersById(init: FetchOptions<paths["/api/v1/hesap/users/{id}"]["put"]>) {
      return client.PUT("/api/v1/hesap/users/{id}", init);
    },
    /**
     * Kullanıcıları listele
     * @route GET /api/v1/hesap/users
     * @permission hesap.user.list
     */
    getUsers(init?: FetchOptions<paths["/api/v1/hesap/users"]["get"]>) {
      return client.GET("/api/v1/hesap/users", init);
    },
    /**
     * Kullanıcı ekle
     * @route POST /api/v1/hesap/users
     * @permission hesap.user.create
     */
    postUsers(init: FetchOptions<paths["/api/v1/hesap/users"]["post"]>) {
      return client.POST("/api/v1/hesap/users", init);
    },
  };
}
