// <auto-generated />
using System;
using Kentos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kentos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditingDbContext))]
    [Migration("20260626040732_InitialAuditing")]
    partial class InitialAuditing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("denetim")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kentos.Infrastructure.Auditing.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Birincil anahtar");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("islem")
                        .HasComment("İşlem türü (Insert/Update/Delete)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("degisiklikler")
                        .HasComment("Alan bazlı değişiklikler [{ field, oldValue, newValue }]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Kayıt zamanı (UTC)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("varlik_id")
                        .HasComment("Kaydın genel kimliği (Uuid)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("varlik_tipi")
                        .HasComment("Değişen varlık tipi (CLR adı)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_adresi")
                        .HasComment("İstemci IP adresi");

                    b.Property<string>("Module")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modul")
                        .HasComment("Modül slug'ı");

                    b.Property<string>("TableName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tablo_adi")
                        .HasComment("Veritabanı tablo adı");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("kullanici_id")
                        .HasComment("İşlemi yapan kullanıcı kimliği");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("kullanici_adi")
                        .HasComment("İşlemi yapan kullanıcı adı");

                    b.HasKey("Id")
                        .HasName("pk_denetim_kayitlari");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_denetim_kayitlari_olusturma_tarihi");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_denetim_kayitlari_varlik_tipi_varlik_id");

                    b.ToTable("denetim_kayitlari", "denetim", t =>
                        {
                            t.HasComment("Veri katmanı denetim kayıtları");
                        });
                });

            modelBuilder.Entity("Kentos.Infrastructure.Errors.ErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Birincil anahtar");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DeveloperNotes")
                        .HasColumnType("text")
                        .HasColumnName("gelistirici_notu")
                        .HasComment("Geliştirici notu");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("istisna_tipi")
                        .HasComment("İstisna tipi (CLR adı)");

                    b.Property<string>("FileName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("dosya_adi")
                        .HasComment("Kaynak dosya adı");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parmakizi")
                        .HasComment("Hata parmak izi (gruplama anahtarı)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ilk_gorulme")
                        .HasComment("İlk görülme zamanı (UTC)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("basliklar")
                        .HasComment("İstek başlıkları (jsonb)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("http_metot")
                        .HasComment("HTTP metodu");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_adresi")
                        .HasComment("İstemci IP adresi");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_gorulme")
                        .HasComment("Son görülme zamanı (UTC)");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("satir_no")
                        .HasComment("Kaynak satır numarası");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mesaj")
                        .HasComment("Hata mesajı");

                    b.Property<string>("Module")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modul")
                        .HasComment("Hatanın oluştuğu modül slug'ı");

                    b.Property<int>("OccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("tekrar_sayisi")
                        .HasComment("Aynı hatanın görülme sayısı");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("koken")
                        .HasComment("Hata kökeni (Server/Client)");

                    b.Property<string>("Path")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("yol")
                        .HasComment("İstek yolu");

                    b.Property<string>("QueryString")
                        .HasColumnType("text")
                        .HasColumnName("sorgu_dizesi")
                        .HasComment("İstek sorgu dizesi");

                    b.Property<string>("Source")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("kaynak")
                        .HasComment("Hata kaynağı (assembly/metot)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("yigin_izi")
                        .HasComment("Yığın izi (stack trace)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("durum")
                        .HasComment("Triyaj durumu (New/Investigating/Resolved/Ignored)");

                    b.Property<int>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("durum_kodu")
                        .HasComment("HTTP durum kodu");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("istemci_bilgisi")
                        .HasComment("İstemci/tarayıcı kimliği (User-Agent)");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("kullanici_id")
                        .HasComment("Kullanıcı kimliği");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("kullanici_adi")
                        .HasComment("Kullanıcı adı");

                    b.HasKey("Id")
                        .HasName("pk_hata_kayitlari");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_hata_kayitlari_parmakizi");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_hata_kayitlari_son_gorulme");

                    b.HasIndex("Origin")
                        .HasDatabaseName("ix_hata_kayitlari_koken");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hata_kayitlari_durum");

                    b.ToTable("hata_kayitlari", "denetim", t =>
                        {
                            t.HasComment("Yakalanan hata kayıtları (parmak izi ile gruplanır)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
