// <auto-generated />
using System;
using Kentos.Modules.Hesap.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kentos.Modules.Hesap.Infrastructure.Migrations
{
    [DbContext(typeof(HesapDbContext))]
    [Migration("20260626070756_InitialHesap")]
    partial class InitialHesap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hesap")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.AccessPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("etki")
                        .HasComment("Etki: Allow (izin) veya Deny (engelle)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tur")
                        .HasComment("Politika türü: Time (zaman) veya Ip (IP)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("oncelik")
                        .HasComment("Değerlendirme önceliği (küçük önce)");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("konu_id")
                        .HasComment("Hedef kullanıcı veya grubun dahili kimliği");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("konu_tipi")
                        .HasComment("Politikanın hedefi: User (kullanıcı) veya Group (grup)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deger")
                        .HasComment("CIDR (IP) veya 'SS:dd-SS:dd' (zaman) değeri");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_erisim_politikalari");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_erisim_politikalari_uuid");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_erisim_politikalari_konu_tipi_konu_id");

                    b.ToTable("erisim_politikalari", "hesap", t =>
                        {
                            t.HasComment("Erişim politikaları (giriş anında IP/zaman kontrolü)");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("eszamanlilik_damgasi")
                        .HasComment("Eşzamanlılık damgası");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("aciklama")
                        .HasComment("Rol açıklaması");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ad")
                        .HasComment("Rol adı");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normal_ad")
                        .HasComment("Normalize edilmiş rol adı");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.HasKey("Id")
                        .HasName("pk_roller");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_roller_uuid");

                    b.ToTable("roller", "hesap", t =>
                        {
                            t.HasComment("Roller");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("basarisiz_giris_sayisi")
                        .HasComment("Ardışık başarısız giriş sayısı");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("eszamanlilik_damgasi")
                        .HasComment("Eşzamanlılık damgası");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ad_soyad")
                        .HasComment("Ad soyad");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("e_posta")
                        .HasComment("E-posta adresi");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("e_posta_dogrulandi")
                        .HasComment("E-posta doğrulandı mı");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("kilit_etkin")
                        .HasComment("Kilitlenebilir mi");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kilit_bitis")
                        .HasComment("Kilit bitiş zamanı");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normal_e_posta")
                        .HasComment("Normalize edilmiş e-posta");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normal_kullanici_adi")
                        .HasComment("Normalize edilmiş kullanıcı adı");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("parola_hash")
                        .HasComment("Parola özeti");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("telefon")
                        .HasComment("Telefon numarası");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("telefon_dogrulandi")
                        .HasComment("Telefon doğrulandı mı");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("guvenlik_damgasi")
                        .HasComment("Güvenlik damgası");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("iki_faktor_etkin")
                        .HasComment("İki faktörlü doğrulama etkin mi");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("kullanici_adi")
                        .HasComment("Kullanıcı adı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.HasKey("Id")
                        .HasName("pk_kullanicilar");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_kullanicilar_uuid");

                    b.ToTable("kullanicilar", "hesap", t =>
                        {
                            t.HasComment("Kullanıcılar");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ad")
                        .HasComment("Departman adı");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("ust_departman_id")
                        .HasComment("Üst departman kimliği (kök için boş)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_departmanlar");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_departmanlar_ad");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_departmanlar_parent_id");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_departmanlar_uuid");

                    b.ToTable("departmanlar", "hesap", t =>
                        {
                            t.HasComment("Departmanlar (ağaç yapısı)");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("eylem")
                        .HasComment("Eylem adı");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("aciklama")
                        .HasComment("Açıklama");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("anahtar")
                        .HasComment("Yetki anahtarı (modul.kaynak.eylem)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("modul")
                        .HasComment("Modül slug");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("kaynak")
                        .HasComment("Kaynak adı");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("baslik")
                        .HasComment("Görünen başlık");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_yetkiler");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_yetkiler_anahtar");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_yetkiler_uuid");

                    b.ToTable("yetkiler", "hesap", t =>
                        {
                            t.HasComment("Yetkiler (sistem tarafından otomatik tanımlanır)");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_kullanma")
                        .HasComment("Son kullanma zamanı (UTC)");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip")
                        .HasComment("Talep eden istemci IP'si");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("iptal_edildi")
                        .HasComment("İptal edildi mi");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<long?>("ReplacedById")
                        .HasColumnType("bigint")
                        .HasColumnName("yerine_gecen_id")
                        .HasComment("Yerine geçen token kimliği (rotasyon)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash")
                        .HasComment("Token SHA-256 özeti (base64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id")
                        .HasComment("Kullanıcı kimliği");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_yenileme_tokenlari");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_yenileme_tokenlari_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_yenileme_tokenlari_user_id");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_yenileme_tokenlari_uuid");

                    b.ToTable("yenileme_tokenlari", "hesap", t =>
                        {
                            t.HasComment("Yenileme tokenları (refresh)");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("yetki_id")
                        .HasComment("Yetki kimliği");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id")
                        .HasComment("Rol kimliği");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_rol_yetkileri");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_rol_yetkileri_permission_id");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_rol_yetkileri_uuid");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_rol_yetkileri_rol_id_yetki_id");

                    b.ToTable("rol_yetkileri", "hesap", t =>
                        {
                            t.HasComment("Rol yetkileri (rol ↔ yetki ataması)");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.UserDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("departman_id")
                        .HasComment("Departman kimliği");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id")
                        .HasComment("Kullanıcı kimliği");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_kullanici_departmanlari");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_kullanici_departmanlari_department_id");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_kullanici_departmanlari_uuid");

                    b.HasIndex("UserId", "DepartmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_kullanici_departmanlari_kullanici_id_departman_id");

                    b.ToTable("kullanici_departmanlari", "hesap", t =>
                        {
                            t.HasComment("Kullanıcı departman üyelikleri");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.UserGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("aciklama")
                        .HasComment("Grup açıklaması");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ad")
                        .HasComment("Grup adı");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_kullanici_gruplari");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_kullanici_gruplari_ad");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_kullanici_gruplari_uuid");

                    b.ToTable("kullanici_gruplari", "hesap", t =>
                        {
                            t.HasComment("Kullanıcı grupları");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.UserGroupMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Dahili sayısal birincil anahtar (API'de gösterilmez)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasComment("Oluşturma zamanı (UTC)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("olusturan")
                        .HasComment("Kaydı oluşturan kullanıcı");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("silme_tarihi")
                        .HasComment("Silme zamanı (UTC)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("silen")
                        .HasComment("Silen kullanıcı");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("grup_id")
                        .HasComment("Grup kimliği");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi_mi")
                        .HasComment("Yumuşak silme işareti");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_veri")
                        .HasComment("Esnek meta veri (jsonb, camelCase anahtarlar)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi")
                        .HasComment("Son güncelleme zamanı (UTC)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("guncelleyen")
                        .HasComment("Son güncelleyen kullanıcı");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id")
                        .HasComment("Kullanıcı kimliği");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv7()")
                        .HasComment("Genel UUIDv7 kimlik (API'de 'id' olarak kullanılır)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("surum")
                        .HasComment("İyimser eşzamanlılık sürüm sayacı");

                    b.HasKey("Id")
                        .HasName("pk_kullanici_grup_uyeleri");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_kullanici_grup_uyeleri_user_id");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_kullanici_grup_uyeleri_uuid");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_kullanici_grup_uyeleri_grup_id_kullanici_id");

                    b.ToTable("kullanici_grup_uyeleri", "hesap", t =>
                        {
                            t.HasComment("Kullanıcı grup üyelikleri");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_rol_iddialari");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_rol_iddialari_role_id");

                    b.ToTable("rol_iddialari", "hesap", t =>
                        {
                            t.HasComment("Rol iddiaları (claims)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_kullanici_iddialari");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_kullanici_iddialari_user_id");

                    b.ToTable("kullanici_iddialari", "hesap", t =>
                        {
                            t.HasComment("Kullanıcı iddiaları (claims)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_kullanici_girisleri");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_kullanici_girisleri_user_id");

                    b.ToTable("kullanici_girisleri", "hesap", t =>
                        {
                            t.HasComment("Harici kullanıcı girişleri");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_kullanici_rolleri");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_kullanici_rolleri_role_id");

                    b.ToTable("kullanici_rolleri", "hesap", t =>
                        {
                            t.HasComment("Kullanıcı rolleri");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_kullanici_tokenlari");

                    b.ToTable("kullanici_tokenlari", "hesap", t =>
                        {
                            t.HasComment("Kullanıcı tokenları");
                        });
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.Department", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departmanlar_departmanlar_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.RefreshToken", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_yenileme_tokenlari_kullanicilar_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.RolePermission", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_yetkileri_yetkiler_permission_id");

                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_yetkileri_roller_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.UserDepartment", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.Department", "Department")
                        .WithMany("Members")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_departmanlari_departmanlar_department_id");

                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_departmanlari_kullanicilar_user_id");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.UserGroupMember", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.UserGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_grup_uyeleri_kullanici_gruplari_group_id");

                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_grup_uyeleri_kullanicilar_user_id");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_iddialari_roller_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_iddialari_kullanicilar_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_girisleri_kullanicilar_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_rolleri_roller_role_id");

                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_rolleri_kullanicilar_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Kentos.Modules.Hesap.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kullanici_tokenlari_kullanicilar_user_id");
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Kentos.Modules.Hesap.Domain.UserGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
